blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/gatotauth
    about: Ask questions and get support from community members.
  - name: Project Security
    url: https://github.com/gatotauth/gatotauth/security/policy
    about: Report security vulnerabilities.
